### ISSUE TITLE
i can't record video with 30fps

### ISSUE THREAD

**Issue by HungPhan2707** [CrazyOrr/FFmpegRecorder#24]
i try to set private int frameRate = 30;
i want to record video 360x360 so i set
private int videoWidth = 360;
    private int videoHeight = 360;
the result video always from 22 to 25.
what i can do to increase frame to exacly when i set at private int frameRate.
ps: i try to change  private static final int PREFERRED_PREVIEW_WIDTH = 640;
    private static final int PREFERRED_PREVIEW_HEIGHT = 360;
i try different value and i realize fps down when i change it..some time i got only 16 17
ps:thanks for your help and iam so sorry for my bad English

**Comment by CrazyOrr** [comment]
Because it takes camera preview frames to record, the result video's fps is determined by the smaller value of `frameRate` you set and `mCamera.getParameters().getPreviewFpsRange()`.

For your question, you can first check your devices' supported preview fps using 
```java
Camera.Parameters parameters = mCamera.getParameters();
parameters.getSupportedPreviewFpsRange();
```
and then set a supported range value that is close to the 'frameRate' you set using 
```java
parameters.setPreviewFpsRange();
mCamera.setParameters(parameters);
```
