### ISSUE TITLE
Tips to reduce Apk size

### ISSUE THREAD

**Issue by levon93** [CrazyOrr/FFmpegRecorder#54]
Hi, thank you for great project.
Can you please provide some tips on how to reduce apk size with proguard ? When adding the dependencies the apk size increased about 50mb.

**Comment by CrazyOrr** [comment]
Proguard [tips](https://github.com/bytedeco/javacv/wiki/Configuring-Proguard-for-JavaCV)
But since most of the size comes from [native libs](https://github.com/CrazyOrr/FFmpegRecorder/blob/ab0a179d2bc09746c9d683ad7b8680c1cbbef130/app/build.gradle#L38-L39), which proguard can't help, you may need to [split your apk per abi](https://developer.android.com/studio/build/configure-apk-splits#configure-abi-split), or even [build](https://github.com/bytedeco/javacpp-presets/wiki/Build-Environments) a more "concise" version on your own.
